apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  selector:
    matchLabels:
      run: reverse-proxy
  replicas: 2
  template:
    metadata:
      labels:
        run: reverse-proxy
    spec:
      containers:
      - name: reverse-proxy
        image: docker.io/tebogoyungmercykay/udagram-reverse-proxy:v0
        ports:
        - containerPort: 80
        resources:
          limits:
            ccpu: 500m
          requests:
            cpu: 200m